# Navigation Links
#   The weight parameter defines the order that the links will appear in.

# main:
#   - name: Home
#     url: /
#     weight: 10
#   - name: Topics
#     url: tags/
#     weight: 20
#   - name: Uses
#     url: uses/
#     weight: 30

main:
  - name: 主页
    url: /
    weight: 10
  - name: 文章
    url: blog/
    weight: 20
  - name: Jetbrains激活
    url: https://jet.dunxuan.xyz
    weight: 30